Parse
CubeRT7/minirt pull request #4
Opened 2023-05-30 23:31 UTC by iijung

#3

2023-06-03 13:14 UTC, sindydwns requested changes

2023-06-03 13:14 UTC, sindydwns commented on src/Element/common.c
> +	if (curr[0] != '\0' && curr[0] != '\r' && curr[0] != ',')
개행`\n`에 대한 처리가 필요합니다.
```suggestion
	if (curr[0] != '\0' && ft_strchr(",\r\n", curr[0]) == NULL)
```

2023-06-03 13:14 UTC, sindydwns commented on src/Element/common.c
> +	if (curr == NULL || (curr[0] != '\0' && curr[0] != '\r'))
개행`\n`에 대한 처리가 필요합니다.
```suggestion
	if (curr == NULL || (curr[0] != '\0' && ft_strchr("\r\n", curr[0]) == NULL))
```

2023-06-03 13:43 UTC, sindydwns reviewed
- `A 1..2..3 255,255,255`
예상: `ratio`가 양식에 맞지 않은 내용으로 파싱에 실패.
결과: `ratio`가 1로 파싱 됨.

- `sp  0,0,20  -1  255,0,0` && `cy  50.0,0.0,20.6  0,0,1.0  -14.2  -21.42  10,0,25`
크기에 해당하는 물리량이 0 보다 작은 케이스에 대해 파싱을 해야하는지에 대한 논의 필요

- `sp 0,0, 20 255,0,0`
예상: 좌표 `z` 정보가 누락되어 파싱에 실패.
결과: `z = 0` 으로 파싱 됨.

2023-06-03 15:56 UTC, iijung commented
> * `A 1..2..3 255,255,255`
>   예상: `ratio`가 양식에 맞지 않은 내용으로 파싱에 실패.
>   결과: `ratio`가 1로 파싱 됨.
> * `sp  0,0,20  -1  255,0,0` && `cy  50.0,0.0,20.6  0,0,1.0  -14.2  -21.42  10,0,25`
>   크기에 해당하는 물리량이 0 보다 작은 케이스에 대해 파싱을 해야하는지에 대한 논의 필요
> * `sp 0,0, 20 255,0,0`
>   예상: 좌표 `z` 정보가 누락되어 파싱에 실패.
>   결과: `z = 0` 으로 파싱 됨.

- #5 
- #6

2023-06-04 07:10 UTC, sindydwns approved these changes
lgtm

2023-06-04 07:10 UTC, merged